name: Test trigger
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - [run-test]
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
